### ISSUE TITLE
About Multi-BLEU

### ISSUE THREAD

**Issue by kadir-gunel** [SwordYork/DCNMT#10]
Hello @SwordYork ,

For evaluating the system, could it be used more than one test sets in just one performance evaluation(bleu)?  I am asking this because the multi-bleu script permits to use more than one test set (it picks a line randomly among different test sets.)

B.R.

**Comment by SwordYork** [comment]
Sorry, I haven't try it. But I think you could do it manually using the multi-bleu script.
