### ISSUE TITLE
FR-EN Datasets

### ISSUE THREAD

**Issue by kadir-gunel** [SwordYork/DCNMT#12]
Hello @SwordYork ,

Could you please share the data for training EN-FR translation system ? 

Thanks in advance
Kadir

**Comment by SwordYork** [comment]
You could download it from [wmt](http://www.statmt.org/wmt15/translation-task.html). There are many pairs of languages.

**Comment by kadir-gunel** [comment]
I checked the site. But at the same time, in your github page you gave a reference to another paper for the dataset and in that paper they made some interesting stuff; first they combined multiple sets and then from that set they took a subset which does not permit me to replicate the same data.

**Comment by SwordYork** [comment]
I see, it is preprocessed by [schwenk](http://www-lium.univ-lemans.fr/~schwenk/nnmt-shared-task/). You could check it.

**Comment by SwordYork** [comment]
By the way, you could send email to me for convenience.

**Comment by kadir-gunel** [comment]
Ok. Thanks.
