### ISSUE TITLE
ImportError :  RECURRENTSTACK_SEPARATOR 

### ISSUE THREAD

**Issue by kadir-gunel** [SwordYork/DCNMT#3]
Hello, 
I am trying to make an experiment with your code. And when I execute 'python training_adam.py', I am getting import errors from blocks : 

**ImportError: No module named 'blocks.bricks.recurrent.misc' ; 'blocks.bricks.recurrent' is not a package.**

 Could you please tell me which version of Blocks are you using? I followed your guide on ReadMe and did not change anything in your code. 
My version of blocks is 0.2.0. 

Thank you in advance

**Comment by kadir-gunel** [comment]
The error occurs in model.py file.

(By the way I tried to execute a blocks-example file and it runs fine.)

**Comment by kadir-gunel** [comment]
In my version of blocks, RECURRENTSTACK_SEPARATOR can be imported from 'blocks.bricks.recurrent' .

**Comment by SwordYork** [comment]
Hi, 
Sorry for the late reply! I think you should update your blocks.

**Comment by ghost** [comment]
Same problem with you and same solution with yours, thank you.
