### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'children'

### ISSUE THREAD

**Issue by kadir-gunel** [SwordYork/DCNMT#4]
Hello, 

After "solving" import error of RECURRENTSTACK_SEPARATOR. I encounterd with a new error in training_adam.py. 

I am running this code inside a virtualenv with python3.5. All the libs are downloaded and are in latest versions.

Could you help please? 

B.R.

**Comment by SwordYork** [comment]
Hi, 
I think it because of an old version of Blocks, it has been fixed in this [PR](https://github.com/mila-udem/blocks/pull/1078) . You could reinstall Blocks as following:
```
pip uninstall blocks
pip install git+git://github.com/mila-udem/blocks.git
```

If you encounter other problems, please feel free to raise questions here.

**Comment by kadir-gunel** [comment]
Thank you! Now it works! :+1:

**Comment by SwordYork** [comment]
@kadir-gunel you are welcome. By the way, the [old version](https://github.com/SwordYork/DCNMT/tree/old-version) is faster and consumes less memory, but the BLEU is a little lower.
