### ISSUE TITLE
Is there a faster way to evaluate the BLEU score ?

### ISSUE THREAD

**Issue by kadir-gunel** [SwordYork/DCNMT#8]
Hello @SwordYork ,

Since there are multiple models for a training, I want to get BLEU score of each model. The testing.py prints each translation and its score one by one. Is there a  way to just print the BLEU score without printing out the scores?

**Comment by SwordYork** [comment]
Sorry, I think the printing of score (cost) is not related to speed. The sampling process has not been optimized, thus may be slower. You could adjust `beam_size` or the validation size. It may take 60 min to translate 3000 sentences.
